spring:
  datasource:
    # Setting mode to PostgreSQL enables compatibility syntax
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        # Enables the web UI at http://localhost:8080/h2-console to view data
        enabled: true
        path: /h2-console
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
aws:
  s3:
    region: us-east-1
    bucket-name: ${S3_BUCKET}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}$
jwt-secret: ${JWT_SECRET}
jwt-expiration-ms: 86400000